FROM node:20-bookworm-slim

RUN apt-get update && apt-get install -y python3 python3-pip ffmpeg openssl --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install yt-dlp --break-system-packages

WORKDIR /app

COPY package*.json ./
COPY apps/web/package*.json apps/web/
COPY apps/worker/package*.json apps/worker/
COPY packages/db/package*.json packages/db/

RUN npm ci

COPY . .

RUN npx prisma generate --schema=packages/db/prisma/schema.prisma

RUN npm run build --workspace=apps/web

EXPOSE 3000

CMD ["npm", "run", "start", "--workspace=apps/web"]
