FROM node:20-alpine

RUN apk add --no-cache curl
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod +x /usr/local/bin/yt-dlp

WORKDIR /app

COPY package*.json ./
COPY apps/web/package*.json apps/web/
COPY apps/worker/package*.json apps/worker/
COPY packages/db/package*.json packages/db/

RUN npm ci

COPY . .

RUN npx prisma generate --schema=packages/db/prisma/schema.prisma

RUN npm run build --workspace=packages/db

RUN npm run build --workspace=apps/web

EXPOSE 3000

CMD ["npm", "run", "start", "--workspace=apps/web"]
